# Generated by Django 4.2.5 on 2023-09-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sen_raum', models.CharField(max_length=45)),
                ('sen_ip', models.CharField(max_length=45)),
                ('sen_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Werte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luftdruck', models.FloatField()),
                ('luftfeuchte', models.FloatField()),
                ('temperatur', models.FloatField()),
                ('datum', models.DateTimeField()),
                ('sensor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='web.sensor')),
            ],
        ),
    ]
