# Generated by Django 4.2.2 on 2023-06-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("sen_id", models.IntegerField(primary_key=True, serialize=False)),
                ("sen_raum", models.CharField(max_length=45)),
                ("sen_ip", models.CharField(max_length=45)),
            ],
            options={"db_table": "sensor", "managed": False,},
        ),
        migrations.CreateModel(
            name="Werte",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("luftdruck", models.FloatField()),
                ("luftfeuchte", models.FloatField()),
                ("temperatur", models.FloatField()),
                ("datum", models.DateTimeField()),
            ],
            options={"db_table": "werte", "managed": False,},
        ),
        migrations.DeleteModel(name="TempValue",),
    ]
