# Generated by Django 4.2.2 on 2023-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("sen_id", models.IntegerField(primary_key=True, serialize=False)),
                ("sen_raum", models.CharField(max_length=45)),
                (
                    "sen_ip",
                    models.GenericIPAddressField(
                        error_messages="IPAdress is not valid!"
                    ),
                ),
            ],
            options={"db_table": "sensor", "managed": False,},
        ),
        migrations.CreateModel(
            name="Werte",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("luftdruck", models.FloatField()),
                ("luftfeuchte", models.FloatField()),
                ("temperatur", models.FloatField()),
                ("datum", models.DateTimeField()),
            ],
            options={"db_table": "werte", "managed": False,},
        ),
    ]
